<?php
/* 

	dgNPCSelectJs.php			-				Dynamically created Javascript needed for select NPC Screen

*/

/*
		PHP executed on load - Note that all PHP in this file is executed
		when the file is loaded, not when JS is called on the page.

		All variables and processing done here. 

		Values inserted into the Javascript in the appropriate place with Echos
*/


		/* Set-up variables for ease of use later */
		$currentNPCNo = getCurrentNPCNo($dgTools);

		$domain_c = 1;
		$domain = "";

		if (isset( $dgTools['NPCsArray'][$currentNPCNo]['domain'][$domain_c] ) ) {
				$domain = $dgTools['NPCsArray'][$currentNPCNo]['domain'][$domain_c];
		}
	 $domain_s = 'getDomainSelectionHTML(' . $domain . ')';

		$classSel = getClassSelectionHTML( $dgTools, 1 );

		$nameid = getNameId(array('NPCsArray', $dgTools['meta']['currentNPCNo'],'classfocus',1), 'classfocus_1');



	/* Returns the JS for classes   */
	
	function getClassesJS($dgTools) {
		$jScript = "/* Generated by getCassesJS php function */";

	 $key_1 = $dgTools['meta']['key_1'];

		$loop = 0;
		$loop = $loop + 1;
		$select = "SELECT class_tp from class2 where mon_key_1 = '$key_1' ORDER BY class_tp";
		$link = getDBLink();;
		$result = mysqli_query($link, $select) ;
		while ($row = mysqli_fetch_array($result)) {
				$type = $row['class_tp'];
	   if ($type != "" and $type != " ") {
	   		$jScript .= 'classArray["';
     	$jScript .= $type . '"] = new Array( ';
					$select2 = "SELECT DISTINCT classf_focus from classfocus2 where classf_class = '$type' and mon_key_1 = '$key_1' " .
                                   "ORDER BY classf_class";
					$link = getDBLink();
					$result2 = mysqli_query($link, $select2) ;
					$var = "";
					while ($row2 = mysqli_fetch_array($result2)) {
		   		$classf_sel = $row2['classf_focus'] ;
       if ($classf_sel != "Tickery Domain"){
		     		$jScript .= '"'.$classf_sel . '", ';
       }
					}

			  	// Get rid of last comma and space
		   $jScript = substr($jScript, 0, -2);
		   $jScript .= "); \n";
				}
		}
		
		$jScript .= "/* END - Generated by getCassesJS php function */";
		return $jScript;
}


/*  END of pure PHP - Javascript or mixed JS/PHP only after this point */
?>

/* Add Onload Event */
window.addEventListener("load", onLoadEvent());

function addElement() {
  var ni = document.getElementById('myDiv');
  var numi = document.getElementById('theValue');
  var num = (document.getElementById('theValue').value -1)+ 2;
  numi.value = num;
  var newclass = document.createElement('div');
  var classIdName = 'my'+num+'Class';
  newclass.setAttribute('id',classIdName);


		var newHTML = '<div class="">';
  newHTML += '<?php echo $classSel; ?>';
  newHTML += '</div>';

  newclass.innerHTML = newHTML;

		ni.appendChild(newclass);


		var newfocus = document.createElement('div');
  var focusIdName = 'my'+num+'Focus';
  newfocus.setAttribute('id',focusIdName);
  newfocus.innerHTML = '<SELECT <?php echo $nameid; ?> ></SELECT>';
  ni.appendChild(newfocus);
}

function removeElement(divNum) {
  var d = document.getElementById('myDiv');
  var olddiv = document.getElementById(divNum.value);
  d.removeChild(olddiv);
}



/* 
		Returns array of valid skill focuses for classes
*/
function getSkillFocusArray( classx ) {

		var classArray = new Array();

<?php
		echo getClassesJS($dgTools)
?>

		return classArray[classx];
}

/*
		Populates the monster type / species selector
*/
function monsterSelection(selectField){
		if ( document.getElementById("mon_name") === null ) {
		}else{
  			var optionsA = document.getElementById("mon_name").options;
				while ( optionsA.length > 0  ) {
						optionsA[0] = null;
     }
   }

  if (selectField.value === "A"){
				var optionsB = document.getElementById("mon_name");
				var selectB = '<?php echo getMonstersByLetter($dgTools,"A")?>';
		}
		if (selectField.value === "B"){
				var optionsB = document.getElementById("mon_name");
				var selectB = '<?php echo getMonstersByLetter($dgTools,"B")?>';
		}
		if (selectField.value === "C"){
				var optionsB = document.getElementById("mon_name");
				var selectB = '<?php echo getMonstersByLetter($dgTools,"C")?>';
				}
			if (selectField.value === "D"){
					var optionsB = document.getElementById("mon_name");
					var selectB = '<?php echo getMonstersByLetter($dgTools,"D")?>';
			}
			if (selectField.value === "E"){
					var optionsB = document.getElementById("mon_name");
					var selectB = '<?php echo getMonstersByLetter($dgTools,"E")?>';
				}
    if (selectField.value === "F"){
					var optionsB = document.getElementById("mon_name");
					var selectB = '<?php echo getMonstersByLetter($dgTools,"F")?>';
				}
				if (selectField.value === "G"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"G")?>';
				}
				if (selectField.value === "H"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"H")?>';
				}
				if (selectField.value === "I"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"I")?>';
				}
				if (selectField.value === "J"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"J")?>';
				}
				if (selectField.value === "K"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"K")?>';
				}
				if (selectField.value === "L"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"L")?>';
				}
				if (selectField.value === "M"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"M")?>';
				}
				if (selectField.value === "N"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"N")?>';
				}
				if (selectField.value === "O"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"O")?>';
				}
				if (selectField.value === "P"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"P")?>';
				}
				if (selectField.value === "Q"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"Q")?>';
				}
				if (selectField.value === "R"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"R")?>';
				}
				if (selectField.value === "S"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"S")?>';
				}
				if (selectField.value === "T"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"T")?>';
				}
				if (selectField.value === "U"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"U")?>';
				}
				if (selectField.value === "V"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"V")?>';
     }
				if (selectField.value === "W"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"W")?>';
				}
				if (selectField.value === "X"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"X")?>';
				}
				if (selectField.value === "Y"){
						var optionsB = document.getElementById("mon_name");
       var selectB = '<?php echo getMonstersByLetter($dgTools,"Y")?>';
     }
				if (selectField.value === "Z"){
						var optionsB = document.getElementById("mon_name");
						var selectB = '<?php echo getMonstersByLetter($dgTools,"Z")?>';
				}
				if (selectField.value === " "){
						var optionsB = document.getElementById("mon_name");
       var selectB = '<?php echo getMonstersByLetter($dgTools,"")?>';
     }

				optionsB.innerHTML = selectB;

}

/*
*				Swaps the domain related HTML
*/	
function replaceDomainField(labelText, classNumber, domainNumber, contents ) {	
				var opID = 	"domain_" + classNumber + domainNumber;
				var opIDLabel = "label_" + opID;
				var labelB = document.getElementById(opIDLabel);
				labelB.innerHTML = labelText;
		
				var optionsB = document.getElementById(opID);
				var optionsBName = optionsB.getAttribute("name");
				var optionsBClass = optionsB.getAttribute("class");
		  var selectB  =  '<SELECT name="';
				selectB += optionsBName + '"';
				selectB += ' id ="'+opID+'" >';
				selectB += contents;
				selectB += '</SELECT>';
		  optionsB.innerHTML = selectB;

}

/*
* Replaces the OPTIONS for the Class Focus and Domains based on the class selected  
*/
function changeField(selectField, classNumber, currentlySelected ) {

			if ( document.getElementById("classfocus_" + classNumber) === null ) {
				return;
			}
	
			/* Get current Options */	
			var optionsA = document.getElementById("classfocus_" + classNumber).options;
			var selectC = document.getElementById("classlevel_" + classNumber);

			/* Clear out focus values */
			while ( optionsA.length > 0  ) {
				optionsA[0] = null;
			}

			/* Set / clear level values */
			var dgLevel = new Array();
			dgLevel[1] = "<?php echo $dgTools['NPCsArray'][getCurrentNPCNo($dgTools)]['classes'][1]['classlevel']; ?>";
			dgLevel[2] = "<?php echo $dgTools['NPCsArray'][getCurrentNPCNo($dgTools)]['classes'][1]['classlevel']; ?>";
			selectC.value = dgLevel[classNumber];
	
			/* Check selected field is valid */
			if (selectField.value != "" && selectField.value !=" " ){
	
				/* Get class focus array */
				var focusArray = getSkillFocusArray(selectField.value) ;
	
				/* Add Option html for class focus */	
				for ( var lp = 0; lp < focusArray.length; lp++ ) {
	
					var optElement = document.createElement( "option" );
					optElement.text = focusArray[lp];
					optElement.value = focusArray[lp];
					optElement.selected = (  focusArray[lp] == currentlySelected ) ;
					optionsA.add(optElement);
	
				}
	
				/* Domains etc */

				/* Clear existing data */
				for  (var domainNumber = 1; domainNumber < 4; domainNumber++ ){
						var optionsB = document.getElementById("wrapper_domain_" + classNumber + domainNumber);
						var selectB  =  '';
						optionsB.innerHTML = selectB;
				}

				/* Set-up variables for data from $dgTools */
				var dgCurrent = new Array();
				dgCurrent[1] = new Array();
				dgCurrent[1][1] = "<?php echo $dgTools['NPCsArray'][getCurrentNPCNo($dgTools)]['classes'][1]['domain'][1]; ?>";
				dgCurrent[1][2] = "<?php echo $dgTools['NPCsArray'][getCurrentNPCNo($dgTools)]['classes'][1]['domain'][2]; ?>";
				dgCurrent[1][3] = "<?php echo $dgTools['NPCsArray'][getCurrentNPCNo($dgTools)]['classes'][1]['domain'][3]; ?>";
				dgCurrent[2] = new Array();
				dgCurrent[2][1] = "<?php echo $dgTools['NPCsArray'][getCurrentNPCNo($dgTools)]['classes'][2]['domain'][1]; ?>";
				dgCurrent[2][2] = "<?php echo $dgTools['NPCsArray'][getCurrentNPCNo($dgTools)]['classes'][2]['domain'][2]; ?>";
				dgCurrent[2][3] = "<?php echo $dgTools['NPCsArray'][getCurrentNPCNo($dgTools)]['classes'][2]['domain'][3]; ?>";

				/* Build arrays of select HTML for convience */
				var selects = new Array();
				selects[1] = new Array();
				selects[2] = new Array();
				selects[1][1] = '<SELECT ' + '<?php echo getNameId(array('NPCsArray',getCurrentNPCNo($dgTools),'classes',1,'domain',1),'domain_11'); ?>' + '>' ;
				selects[1][1] = '<SELECT ' + '<?php echo getNameId(array('NPCsArray',getCurrentNPCNo($dgTools),'classes',1,'domain',1),'domain_11'); ?>' + '>' ;
				selects[1][2] = '<SELECT ' + '<?php echo getNameId(array('NPCsArray',getCurrentNPCNo($dgTools),'classes',1,'domain',2),'domain_12'); ?>' +  '>' ;
				selects[1][3] = '<SELECT ' + '<?php echo getNameId(array('NPCsArray',getCurrentNPCNo($dgTools),'classes',1,'domain',3),'domain_13'); ?>' +  '>' ;
				selects[2][1] = '<SELECT ' + '<?php echo getNameId(array('NPCsArray',getCurrentNPCNo($dgTools),'classes',2,'domain',1),'domain_21'); ?>' +  '>' ;
				selects[2][2] = '<SELECT ' + '<?php echo getNameId(array('NPCsArray',getCurrentNPCNo($dgTools),'classes',2,'domain',2),'domain_22'); ?>' +  '>' ;
				selects[2][3] = '<SELECT ' + '<?php echo getNameId(array('NPCsArray',getCurrentNPCNo($dgTools),'classes',2,'domain',3),'domain_23'); ?>' +  '>' ;
				var hiddens = new Array();
				hiddens[1] = new Array();
				hiddens[2] = new Array();
				hiddens[1][1] = '<INPUT TYPE="hidden" VALUE="" ' + '<?php echo getNameId(array('NPCsArray',getCurrentNPCNo($dgTools),'classes',1,'domain',1),'domain_11'); ?>' + '">' ;
				hiddens[1][2] = '<INPUT TYPE="hidden" VALUE="" ' + '<?php echo getNameId(array('NPCsArray',getCurrentNPCNo($dgTools),'classes',1,'domain',2),'domain_12'); ?>' + '">' ;
				hiddens[1][3] = '<INPUT TYPE="hidden" VALUE="" ' + '<?php echo getNameId(array('NPCsArray',getCurrentNPCNo($dgTools),'classes',1,'domain',3),'domain_13'); ?>' + '">' ;
				hiddens[2][1] = '<INPUT TYPE="hidden" VALUE="" ' + '<?php echo getNameId(array('NPCsArray',getCurrentNPCNo($dgTools),'classes',2,'domain',1),'domain_21'); ?>' + '">' ;
				hiddens[2][2] = '<INPUT TYPE="hidden" VALUE="" ' + '<?php echo getNameId(array('NPCsArray',getCurrentNPCNo($dgTools),'classes',2,'domain',2),'domain_22'); ?>' + '">' ;
				hiddens[2][3] = '<INPUT TYPE="hidden" VALUE="" ' + '<?php echo getNameId(array('NPCsArray',getCurrentNPCNo($dgTools),'classes',2,'domain',3),'domain_23'); ?>' + '">' ;

				/* Build array of classes / domains */
				var options = new Array();

				options["Wizard"] = new Array();
				options["Wizard"][1] = new Array();
				options["Wizard"][1]["label"] = "Wizard School";
				options["Wizard"][1]["values"] = '<?php echo getSchoolSelectionHTML(""); ?>';
				options["Wizard"][2] = new Array();
				options["Wizard"][2]["label"] = "Prohibited 1";
				options["Wizard"][2]["values"] = '<?php echo getSchoolSelectionHTML(""); ?>';
				options["Wizard"][3] = new Array();
				options["Wizard"][3]["label"] = "Prohibited 2";
				options["Wizard"][3]["values"] = '<?php echo getSchoolSelectionHTML(""); ?>';
				options["Cleric"] = new Array();
				options["Cleric"][1] = new Array();
				options["Cleric"][1]["label"] = "Cleric Domain 1";
				options["Cleric"][1]["values"] = '<?php echo getDomainSelectionHTML(""); ?>';
				options["Cleric"][2] = new Array();
				options["Cleric"][2]["label"] = "Cleric Domain 2";
				options["Cleric"][2]["values"] = '<?php echo getDomainSelectionHTML(""); ?>';				options["Psion"] = new Array();
				options["Psion"][1] = new Array();
				options["Psion"][1]["label"] = "Psionic Discilpine";
				options["Psion"][1]["values"] = '<?php echo getPsionSelectionHTML(""); ?>';

<?php
		/*  PATHFINDER ONLY */
		if ($dgTools['meta']['key_1'] == PATHFINDER){

?>

				options["Sorcerer"] = new Array();
				options["Sorcerer"][1] = new Array();
				options["Sorcerer"][1]["label"] = "Bloodline";
				options["Sorcerer"][1]["values"] = '<?php echo getBloodlineSelectionHTML(""); ?>';
				options["Oracle"] = new Array();
				options["Oracle"][1] = new Array();
				options["Oracle"][1]["label"] = "Mystery";
				options["Oracle"][1]["values"] = '<?php echo getOracleSelectionHTML(""); ?>';
				options["Oracle"][2] = new Array();
				options["Oracle"][2]["label"] = "Curse";
				options["Oracle"][2]["values"] = '<?php echo getOracleCurseSelectionHTML(""); ?>';
				options["Cavalier"] = new Array();
				options["Cavalier"][1] = new Array();
				options["Cavalier"][1]["label"] = "Order";
				options["Cavalier"][1]["values"] = '<?php echo getOrderSelectionHTML(""); ?>';
				options["Cavalier"][2] = new Array();
				options["Cavalier"][2]["label"] = "Archetype";
				options["Cavalier"][2]["values"] = '<?php echo getCavalierSelectionHTML(""); ?>';
				options["Samurai"] = new Array();
				options["Samurai"][1] = new Array();
				options["Samurai"][1]["label"] = "Order";
				options["Samurai"][1]["values"] = '<?php echo getOrderSelectionHTML(""); ?>';
				options["Witch"] = new Array();
				options["Witch"][1] = new Array();
				options["Witch"][1]["label"] = "Patron";
				options["Witch"][1]["values"] = '<?php echo getPatronSelectionHTML(""); ?>';
				options["Bloodrager"] = new Array();
				options["Bloodrager"][1] = new Array();
				options["Bloodrager"][1]["label"] = "Patron";
				options["Bloodrager"][1]["values"] = '<?php echo getBloodragerSelectionHTML(""); ?>';
				options["Inquisitor"] = new Array();
				options["Inquisitor"][1] = new Array();
				options["Inquisitor"][1]["label"] = "Cleric Domain";
				options["Inquisitor"][1]["values"] = '<?php echo getDomainSelectionHTML(""); ?>';
				options["Psychic Warrior"] = new Array();
				options["Psychic Warrior"][1] = new Array();
				options["Psychic Warrior"][1]["label"] = "Warrior Path";
				options["Psychic Warrior"][1]["values"] = '<?php echo getPsyWarrSelectionHTML(""); ?>';
				options["Ranger"] = new Array();
				options["Ranger"][1] = new Array();
				options["Ranger"][1]["label"] = "Archetype";
				options["Ranger"][1]["values"] = '<?php echo getRangerSelectionHTML(""); ?>';
				options["Rogue"] = new Array();
				options["Rogue"][1] = new Array();
				options["Rogue"][1]["label"] = "Archetype";
				options["Rogue"][1]["values"] = '<?php echo getRogueSelectionHTML(""); ?>';
				options["Druid"] = new Array();
				options["Druid"][1] = new Array();
				options["Druid"][1]["label"] = "Archetype";
				options["Druid"][1]["values"] = '<?php echo getDruidSelectionHTML(""); ?>';
				options["Druid"][2] = new Array();
				options["Druid"][2]["label"] = "Domain (Only if no Animal Companion)";
				options["Druid"][2]["values"] = '<?php echo getDruidDomainSelectionHTML(""); ?>';
				options["Bard"] = new Array();
				options["Bard"][1] = new Array();
				options["Bard"][1]["label"] = "Archetype";
				options["Bard"][1]["values"] = '<?php echo getRogueSelectionHTML(""); ?>';
				options["Barbarian"] = new Array();
				options["Barbarian"][1] = new Array();
				options["Barbarian"][1]["label"] = "Archetype";
				options["Barbarian"][1]["values"] = '<?php echo getBarbarianSelectionHTML(""); ?>';
				options["Fighter"] = new Array();
				options["Fighter"][1] = new Array();
				options["Fighter"][1]["label"] = "Archetype";
				options["Fighter"][1]["values"] = '<?php echo getFighterSelectionHTML(""); ?>';
				options["Monk"] = new Array();
				options["Monk"][1] = new Array();
				options["Monk"][1]["label"] = "Archetype";
				options["Monk"][1]["values"] = '<?php echo getMonkSelectionHTML(""); ?>';
				options["Gunslinger"] = new Array();
				options["Gunslinger"][1] = new Array();
				options["Gunslinger"][1]["label"] = "Archetype";
				options["Gunslinger"][1]["values"] = '<?php echo getGunslingerSelectionHTML(""); ?>';
				options["Summoner"] = new Array();
				options["Summoner"][1] = new Array();
				options["Summoner"][1]["label"] = "Archetype";
				options["Summoner"][1]["values"] = '<?php echo getSummonerSelectionHTML(""); ?>';
				options["Alchemist"] = new Array();
				options["Alchemist"][1] = new Array();
				options["Alchemist"][1]["label"] = "Archetype";
				options["Alchemist"][1]["values"] = '<?php echo getAlchemistSelectionHTML(""); ?>';
				options["Warpriest"] = new Array();
				options["Warpriest"][1] = new Array();
				options["Warpriest"][1]["label"] = "Blessing 1";
				options["Warpriest"][1]["values"] = '<?php echo getwarpriestSelectionHTML(""); ?>';
				options["Warpriest"][2] = new Array();
				options["Warpriest"][2]["label"] = "Blessing 2";
				options["Warpriest"][2]["values"] = '<?php echo getwarpriestSelectionHTML(""); ?>';

<?php
	}			/* End - PAthfinder Only */
?>

				/* Is it a class we are interested in? */
				if ( selectField.value in options ) {
						/* Add HTML to form */
						for (var domainNumber =1; domainNumber < 4; domainNumber++) {
								var selector = "wrapper_domain_" + classNumber + domainNumber;
								var optionsB = document.getElementById(selector);
								if (typeof options[selectField.value][domainNumber] !== 'undefined' ) {
										/* We have a domain  */
										var selectB = options[selectField.value][domainNumber]["label"] + " ";
										selectB += selects[classNumber][domainNumber];
										selectB += options[selectField.value][domainNumber]["values"];
										selectB += "</SELECT>";
										optionsB.innerHTML = selectB;
										/* Set to last value if valid */
										var mySelect = document.querySelector('#' + selector + " > select");
										var myOpts = mySelect.options;
										var exists = false;
										for (var lp = 0; lp < myOpts.length; lp++ ) {
												if (myOpts[lp].value === dgCurrent[classNumber][domainNumber]) {
														exists = true;
														myOpts[lp].setAttribute('selected', true); 	
														break;
												}
										}
										if ( !exists) {
												myOpts[0].setAttribute('selected',true);
										}
								} else {
										/* Add hidden fields to make sure all old domain data is cleared in the $_Post */
										optionsB.innerHTML = hiddens[classNumber][domainNumber];
								}
						}
				}


/****  

		ARCHMAGE ????? <-----   WHAT DOES This DO ?????? 

******/

			if (selectField.value  == "Archmage" || selectField.value  == "Hierophant"){
        //                   alert ("Archmage");
                          // gets old options i.e 1-10
						var optionsA = document.getElementById("classlevel_" + classNumber).options;
		//alert (optionsA);

		/* Clear out old values */
      while ( optionsA.length > 0  ) {
		      optionsA[0] = null;
      }
<?PHP
			$count = 0;
			$html = "";
			while ($count < 5){
   			$count +=1;
					$html .= '<OPTION VALUE="'.$count.'"  >'.$count.'</OPTION>';
			}
?>

   var optionsB = document.getElementById("classlevel_" + classNumber);
   var selectB = '<SELECT class="" NAME="classLevel_' + classNumber + '" id="classlevel_' + classNumber + '">' + '<? echo $html; ?>';
   optionsB.innerHTML = selectB;

   var optionsC = document.getElementById("classlevel_" + classNumber).options;
   for  (var Number = 1; Number < 6; Number++ ){
		 			optionsC[Number -1].selected = false;
   }
   optionsC.select.selectedIndex = currentlySelected -1 ;
			}


		} /* End of select field check */
}





	/*  Load the Skill Focus when the page is loaded as this cannot be done before */
function onLoadEvent() {

<?php
		/* DEBUG CODE - Remove for Live system */
		$js = 'console.log("';
		$val = var_export($dgTools,1);
		$val = str_replace(array("\r\n", "\n", "\r"),"",$val);  /* remove carriage returns */
		$val = str_replace('"',"'",$val);  /* swap double quotes for single quotes */
		$js .= $val;
		$js .= '");';
		echo $js;
		/* DEBUG CODE - END */
?>

<?php

		$npcNo = getCurrentNPCNo($dgTools);
		$classes = $dgTools["NPCsArray"][$npcNo]["classes"];


		$count = 1;
		foreach($classes as $class) {
				if ( isset( $class["class_tp"] ) ) {
						$field = "class_tp_".$count;
						$value = $class["classfocus"];
				// Call Javascript to populate field
?>

		var myCount = "<?php echo $count; ?>";
		var myValue = "<?php echo $value; ?>";
//console.log(myField);
//console.log("<?php echo $field; ?>");
		var myField = document.getElementById("<?php echo $field; ?>");
//console.log(myValue);

		if ( myField ) {
			changeField( myField, myCount, myValue );  
		}
<?php

				}
			$count++;
		}

?>

}  /* onLoadEvent End */